mots = [
    "abeille", "abricot", "agenda", "aigle", "aimer", "algue", "amour", "ancien", "animal", "arbre",
    "arcade", "armure", "artiste", "autobus", "avion", "bagage", "banane", "barrage", "bataille", "bateau",
    "batterie", "bijou", "blague", "blanc", "bois", "bonjour", "botte", "bouche", "bouteille", "brouillard",
    "bulle", "bureau", "cabane", "cactus", "cadeau", "cafe", "calendrier", "camera", "campagne", "canard",
    "caneton", "carotte", "carte", "cascade", "casque", "cassette", "chat", "chaud", "chemin", "chien",
    "chiffre", "chocolat", "ciel", "clavier", "cle", "cloche", "coffre", "coing", "colis", "compote",
    "coq", "corail", "cornet", "corps", "coton", "crabe", "crayon", "cuisine", "cure", "danse",
    "debut", "dent", "dessin", "diamant", "dinde", "dodo", "doigt", "dollar", "drapeau", "echelle",
    "eclair", "ecole", "ecran", "ecriture", "effort", "elephant", "emission", "endroit", "enfant", "enveloppe",
    "epaule", "epice", "escalier", "essence", "etoile", "faible", "faim", "famille", "fantome", "femme",
    "fenetre", "feu", "ficelle", "filet", "film", "flamme", "fleur", "flocon", "flute", "foret",
    "formule", "four", "fourchette", "frere", "fruit", "garage", "gateau", "gazon", "geste", "gilet",
    "glace", "globe", "gomme", "gorille", "grain", "grandeur", "grenouille", "gris", "guitare", "habitude",
    "herbe", "hibou", "histoire", "homme", "horizon", "horloge", "hotel", "huile", "huitre", "idee",
    "igloo", "image", "immeuble", "insecte", "instant", "instrument", "internet", "jardin", "jeu", "jouet",
    "jus", "koala", "lac", "lampe", "lapin", "lave", "lien", "linge", "lion", "livre",
    "loup", "lune", "lutin", "machine", "magie", "magnet", "main", "maison", "maman", "manette",
    "manger", "manteau", "marche", "masque", "matin", "mauvais", "medaille", "melange", "merci", "miroir",
    "mode", "montagne", "montre", "moteur", "mouette", "mousse", "mouton", "mur", "musique", "navire",
    "neige", "nez", "ninja", "nord", "nuage", "objet", "océan", "oeuf", "ombre", "ongle",
    "ordinateur", "oreille", "outil", "ours", "outil", "page", "pain", "panier", "papier", "parfum",
    "parole", "partie", "patate", "pays", "peche", "peinture", "peluche", "perle", "personne", "petit",
    "photo", "piano", "piece", "pierre", "pinceau", "piscine", "plage", "plante", "plateau", "pluie",
    "poids", "poire", "poisson", "pomme", "pont", "porte", "poubelle", "poulet", "poupée", "poussin",
    "poussiere", "pouvoir", "prenom", "prise", "prison", "projet", "pull", "question", "queue", "radio",
    "raisin", "ranger", "rayon", "rectangle", "regle", "renard", "repas", "requin", "reseau", "retraite",
    "reve", "rideau", "rire", "robot", "robe", "rocher", "roi", "ronron", "rose", "roulette",
    "rouge", "ruche", "ruine", "sac", "sable", "saison", "salade", "salle", "salon", "sapin",
    "savon", "science", "scorpion", "sculpture", "secret", "serpent", "sieste", "signal", "silence", "sirene",
    "site", "skate", "snack", "societe", "soleil", "souris", "sport", "station", "stylo", "sucre",
    "sujet", "support", "surf", "table", "taille", "tapis", "tasse", "tempete", "temps", "tennis",
    "terre", "test", "texte", "ticket", "tigre", "titre", "toile", "tomate", "tonnerre", "train",
    "triangle", "trou", "trousse", "tshirt", "tulipe", "univers", "usage", "vache", "valise", "vase",
    "velo", "vent", "verre", "veste", "village", "ville", "violon", "vitamine", "vitesse", "voiture",
    "volant", "volcan", "voyage", "wagon", "zebre", "zoo", "zone"
]
